<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="rwahsglobalnav">
    <div id="cross-site" class="panel nav-tabs header">
        <div class="subsites-entry" role="navigation">
            <ul class="nav nav-tabs">
                <li role="presentation"><a href="https://www.histwest.org.au/" class="cross-site-link">Website</a></li>
                <li role="presentation" class="active"><a href="https://shop.histwest.org.au/" class="active">Shop</a></li>
                <li role="presentation"><a href="https://research.histwest.org.au/" class="cross-site-link">Collections</a></li>
            </ul>
        </div>
    </div>
</div>