<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="rwahsglobalnav">
    <ul class="nav nav-tabs">
        <li role="presentation"><a href="https://www.histwest.org.au">Website</a></li>
        <li role="presentation"><a href="https://research.histwest.org.au">Collections</a></li>
        <li role="presentation" class="active"><a href="https://shop.histwest.org.au">Shop</a></li>
    </ul>
</div>